packages:
  - apps/*
  - libs/*
  - scripts/generate-app/templates/*

injectWorkspacePackages: true

allowBuilds:
  '@scarf/scarf': true
  msgpackr-extract: true
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  core-js: false
  core-js-pure: false
  esbuild: true
  sharp: true
  unrs-resolver: true
