# ---------- Build stage ----------
FROM node:22-alpine AS build

# Install build dependencies
RUN apk update && apk add --no-cache \
    build-base \
    gcc \
    autoconf \
    automake \
    zlib-dev \
    libpng-dev \
    vips-dev \
    git > /dev/null 2>&1

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /opt/

# Copy only manifest files (pnpm uses pnpm-lock.yaml)
COPY package.json pnpm-lock.yaml ./

# Important: pnpm creates a global store, ensure it is inside the container
ENV PNPM_HOME="/opt/.pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install dependencies
# use --prod (or --filter...) as replacement for npm install --only=production
RUN pnpm install --prod --frozen-lockfile

WORKDIR /opt/app
COPY . .

# Build project
RUN pnpm build


# ---------- Final production image ----------
FROM node:22-alpine

# Install runtime dependencies
RUN apk add --no-cache vips-dev

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/

# Copy node_modules from build
COPY --from=build /opt/node_modules ./node_modules
COPY --from=build /opt/.pnpm /.pnpm

WORKDIR /opt/app

# Copy application build output
COPY --from=build /opt/app ./

ENV PATH=/opt/node_modules/.bin:$PATH

# Permissions and startup
RUN chown -R node:node /opt/app
USER node
EXPOSE 1337
CMD ["pnpm", "start"]
