name: Gitleaks Security Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gitleaks:
    # Always scan pushes to main & skip PRs opened from forks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
